<?php foreach($this->getUploadedImages() as $image): ?>
    <img src="<?php echo $this->getImageUrl($image['image']); ?>"
         data-origin-url="<?php echo $this->getOriginImageUrl($image['image']); ?>"
         class="clipart-image" alt="" title=""/>
<?php endforeach; ?>
<div id="upload-image-error" <?php if (!$this->getError()):?>style="display: none" <?php endif;?>>
    <?php if ($text = $this->getError()): ?>
        <p><?php echo $text;?></p>
    <?php endif;?>
</div>
