<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
          <?php echo Mage::helper('designer')->__('Product Designer Settigns') ?>
        </h4>
    </div>
    <fieldset class="fieldset fieldset-wide" id="product_designer_fields">
      <div class="hor-list">
        <table cellspacing="0" class="form-list">
          <tr>
            <td class="label"><label for="enable_product_designer"><?php echo Mage::helper('designer')->__('Remove Add To Cart Button') ?></label></td>
            <td class="value">
                <!--<select id="enable_product_designer" name="product[enable_product_designer]" class=" select">
                  <option value="0" selected="selected"><?php /*echo $this->__('No') */?></option>
                  <option value="1"><?php /*echo $this->__('Yes') */?></option>
                </select>-->
            </td>
            <td class="scope-label"><span class="nobr"><?php echo Mage::helper('designer')->__('Remove Add To Cart Button from category view') ?></span></td>
          </tr>
        </table>
      </div>
    </fieldset>
</div>
