<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use/
 * @version      Release: 2.1.0
 * @since        Available since Release 1.0.0
 */
?>
<div class="content-header">
    <h3 class="icon-head head-categories"><?php echo Mage::helper('gomage_designer')->__($this->htmlEscape($this->getHeader())) ?> <a target="_blank" href="https://wiki.gomage.com/display/PD/Internet+Explorer+Compatible+Fonts">GoMage ProductDesigner WiKi</a></h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getSaveButtonHtml() ?>
    </p>
</div>
<div>
    <form id="cliparts_edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <?php echo $this->getChildHtml('gallery'); ?>
    </form>
</div>
<script>
    function categorySubmit() {
        $('cliparts_edit_form').submit();
    }
</script>