<?php
    $_designCollection=$this->getDesignCollection();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_designCollection->getSize();
?>
<?php if(!$_collectionSize): ?>
    <p class="note-msg"><?php echo $this->__('You have no designed products') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_designCollection as $_design): ?>
            <?php $_product = $_design->getProduct(); ?>
            <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid">
            <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getDesignedProductUrl($_design->getDesignId()) ?>" title="<?php //echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->getImage($_design); ?>" width="135" height="135" alt="<?php //echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <h2 class="product-name">
                    <a href="<?php echo $_product->getDesignedProductUrl($_design->getDesignId()); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                </h2>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
            <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php endif; ?>