<div>
    <div>
        <div class="notes-panel-title">Additional instructions</div>
    </div>
    <div>
        <textarea class="notes-panel-textarea" cols="5" rows="18"></textarea>

        <div class="pd-element-wrapper pd-social-icons">
            <img class="pd-email-icon" src="/skin/frontend/base/default/images/gomage/productdesigner/social/email.png">
            <img class="pd-twitter-icon" src="/skin/frontend/base/default/images/gomage/productdesigner/social/twitter.png">
            <img class="pd-facebook-icon" src="/skin/frontend/base/default/images/gomage/productdesigner/social/facebook.png">
        </div>
    </div>
</div>