<?php
/**
 * @see GoMage_ProductDesigner_Block_Design_Design
 * @var $this GoMage_ProductDesigner_Block_Design_Design
 *
 * @var $clipartsPath string
 * @var $images array
 * @var $colors array
 * @var $mainCategories GoMage_ProductDesigner_Model_Mysql4_Clipart_Category_Collection
 * @var $subCategories GoMage_ProductDesigner_Model_Mysql4_Clipart_Category_Collection
 */
?>

<div id="cliparts-filters" class="cliparts-filters">
    <?php echo $this->getChildHtml('design.filters'); ?>
</div>

<div id="cliparts-list" class="cliparts-list">
    <?php echo $this->getChildHtml('design.cliparts');?>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function(e){
        var Designer = new GoMage.Designer('<?php echo Mage::getUrl('*/index/filterCliparts');?>');
    }.bind(this));
</script>