<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2018 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use/
 * @version      Release: 2.6.0
 * @since        Available since Release 1.0.0
 */
?>
<div id="cliparts-filters" class="cliparts-filters">
    <?php echo $this->getChildHtml('design.filters'); ?>
</div>

<div id="cliparts-list" class="cliparts-list">
    <?php echo $this->getChildHtml('design.cliparts');?>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function(e){
        var Designer = new GoMage.Designer('<?php echo Mage::getUrl('*/index/filterCliparts');?>');
    }.bind(this));
</script>