<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2016 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use/
 * @version      Release: 2.4.0
 * @since        Available since Release 1.0.0
 */
?>
<div id="navigation_panel">
    <div id="navigation-filters">
        <?php echo $this->getFiltersHtml(); ?>
    </div>

    <div id="navigation_listing">
        <?php echo $this->getProductListHtml(); ?>
    </div>
</div>
<script type="text/javascript">
    document.observe('dom:loaded', function(e){
        new GoMage.ProductNavigation(
            '<?php echo Mage::getUrl('*/index/filterProducts')?>',
            '<?php echo Mage::getUrl('*')?>'
        );
    }.bind(this));
</script>