<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2017 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use/
 * @version      Release: 2.5.0
 * @since        Available since Release 1.0.0
 */
?>
<?php
$colors = $this->getAvailableColors();
$defaultFonts = $this->getDefaultFonts();
$fonts = $this->getFonts();
$sizes = $this->getFontSizes();
?>
<style type="text/css">
<?php foreach($fonts as $font):?>
    @font-face {
        font-family: <?php echo $font;?>;
    }
<?php endforeach;?>
@font-face {
    font-family: "Liberation Mono";
    src: url("<?php echo $this->getFontUrl('LiberationMono-Regular.ttf');?>");
}
@font-face {
    font-family: "Liberation Sans";
    src: url("<?php echo $this->getFontUrl('LiberationSans-Regular.ttf');?>");
}
@font-face {
    font-family: "Liberation Sans Narrow";
    src: url("<?php echo $this->getFontUrl('LiberationSansNarrow-Regular.ttf');?>");
}
@font-face {
    font-family: "Liberation Serif";
    src: url("<?php echo $this->getFontUrl('LiberationSerif-Regular.ttf');?>");
}
</style>
<div>
    <div class="pd-element-wrapper">
        <textarea id="add_text_textarea" class="pd-textarea" placeholder="<?php echo $this->__('Enter text here') ?>"></textarea>
    </div>
    <div class="pd-element-wrapper">
      <div class="pd-text-font-left">
        <select class="font-picker pd-select" id="font-selector">
        <?php foreach ($defaultFonts as $font):?>
            <option value="<?php echo $font['value']; ?>" <?php echo $this->getDefaultFontFamily() == $font['value'] ? 'selected="selected"' : ''?>><?php echo $font['label']; ?></option>
        <?php endforeach;?>
        <?php foreach($fonts as $font): ?>
            <option value="<?php echo $font; ?>"><?php echo $font; ?></option>
        <?php endforeach; ?>
        </select>
      </div>
      <div class="pd-text-font-right">
        <select class="font-size-selector pd-select" id="font_size_selector">
            <?php foreach ($sizes as $size):?>
                <option value="<?php echo $size; ?>" <?php echo $this->getDefaultFontSize() == $size ? 'selected="selected"' : ''?>><?php echo $size; ?></option>
            <?php endforeach;?>
        </select>
      </div>

    </div>
    <div class="pd-element-wrapper">
        <button class="panel-btn pd-btn-bold" id="add_text_btn_bold"><?php echo $this->__('B'); ?></button>
        <button class="panel-btn pd-btn-italic" id="add_text_btn_italic"><?php echo $this->__('I'); ?></button>
        <button class="panel-btn pd-btn-underline" id="add_text_btn_underline"><?php echo $this->__('U'); ?></button>
        <button class="panel-btn pd-btn-stroke-through" id="add_text_btn_stroke_through"><?php echo $this->__('S'); ?></button>
        <span class="panel-btn-sep"></span>

        <?php if ($this->effectsEnabled()):?>
            <button id="outline-button" class="panel-btn2"><?php echo $this->__('Outline'); ?></button>
            <button id="shadow-button" class="panel-btn2"><?php echo $this->__('Shadow'); ?></button>
            <div class="pd-text-effect-popup">
                <fieldset class="shadow-config text-effect">
                    <legend><?php echo $this->__('Shadow'); ?></legend>
                    <div id="shadow-cancel" title="<?php echo $this->__('Cancel Shadow') ?>" data-effect="shadow" class="panel-cancel-btn">&times;</div>
                    <div class="pd-element-wrapper">
                        <label><?php echo $this->__('Offset Y'); ?>: </label>
                        <input type="range" value="0" id="shadow_y_range" min="-25" max="25" step="1">
                    </div>
                    <div class="pd-element-wrapper">
                        <label><?php echo $this->__('Offset X'); ?>: </label>
                        <input type="range" value="0" id="shadow_x_range" min="-25" max="25" step="1">
                    </div>
                    <div class="pd-element-wrapper">
                        <label><?php echo $this->__('Blur'); ?>: </label>
                        <input type="range" value="0" id="shadow_blur" min="0" max="50" step="1">
                    </div>
                    <div class="pd-element-wrapper">
                        <canvas height="40" width="288" id="textShadow" class="color-picker"></canvas>
                    </div>
                </fieldset>
                <fieldset class="outline-config text-effect">
                    <legend><?php echo $this->__('Outline'); ?></legend>
                    <div id="outline-cancel" title="<?php echo $this->__('Cancel Outline') ?>" data-effect="outline" class="panel-cancel-btn">&times;</div>
                    <div class="pd-element-wrapper">
                        <label><?php echo $this->__('Size')?>:</label>
                        <input type="range" value="0" id="outline_range" min="0" max="3" step="0.05">
                    </div>
                    <div class="pd-element-wrapper">
                        <canvas height="40" width="288" id="strokeStyle" class="color-picker"></canvas>
                    </div>
                </fieldset>
            </div>
        <?php endif; ?>
    </div>

    <div class="colors-panel" id="add_text_colors_panel">
        <?php foreach($colors as $color): ?>
            <span class="color-btn color-code-<?php echo $color; ?>" style="background-color:#<?php echo $color; ?>">&nbsp;</span>
        <?php endforeach; ?>
        <span class="color-picher"></span>
    </div>
    <div class="pd-element-wrapper color-picker-palitra" id="color-picker-palitra" style="display: none;">
        <canvas height="69" width="290" id="color" class="color-picker"></canvas>
    </div>
    <div class="pd-element-wrapper pd-add-text-actions">
        <button id="add_text_button" class="pd-btn pd-btn-green pd-btn-add-text"><?php echo $this->__('Add Text'); ?></button>
    </div>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function(e){
        new GoMage.TextEditor('<?php echo $this->getDefaultFontFamily();?>', '<?php echo $this->getDefaultFontSize()?>');
    }.bind(this))
    var fonts = '<?php echo $this->getImplodedFontsString();?>'.split(',');
    if (fonts != '') {
        WebFontConfig = {
            custom: {
                families: fonts
            }
        };

        (function() {
            var wf = document.createElement('script');
            wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js';
            wf.type = 'text/javascript';
            wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })();
    }
</script>
