<?php $licenseEnabled =  $this->licenseAgreementsEnabled() && $this->getLicenceAgreementsText(); ?>
<div>
    <div id="uploadedImages">
        <?php echo $this->getChildHtml('uploadedImages'); ?>
    </div>
    <?php if ($licenseEnabled):?>
    <ul class="form-list">
      <li class="control control-rights">
        <input type="checkbox" class="checkbox" name="licence_agreements" id="licence_agreements" />
        <label for="licence_agreements"><?php echo $this->__('I have the rights to use these images') ?></label>
      </li>
    </ul>
    <div class="pd_more_info_link">
        <a href="javascript:;" id="license-agreements-link"><?php echo $this->__('More info') ?></a>
        <div id="license-agreemants" class="pd-license-agreements-popup" style="display: none">
            <?php echo $this->getLicenceAgreementsText(); ?>
        </div>
    </div>
    <?php endif;?>
</div>
<div id="file-input-box" <?php echo $licenseEnabled ? 'style="display:none;"' : ''?>>
    <form target="iframeSave" id="uploadImages" enctype="multipart/form-data" action="<?php echo Mage::getUrl('designer/index/uploadImages'); ?>" method="post">
        <input name="filesToUpload[]" id="filesToUpload" type="file" multiple="multiple" accept="<?php echo $this->getAllowedImageMimeTypesString(); ?>"/>
        <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getMaxUploadFileSize();?>" />
        <button class="button" type="submit"><span><span><?php echo $this->__('Save'); ?></span></span></button>
        <iframe id="iframeSave" name="iframeSave" style="display:none;"></iframe>
    </form>
    <?php if ($this->imageConditionsEnabled() && $text = $this->getImageConditionsText()): ?>
        <div id="image-conditions">
            <?php echo $text; ?>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
    document.observe('dom:loaded', function(e){
        var imagesUploader = new GoMage.ImageUploader(
            '<?php echo $this->getMaxUploadFileSize();?>',
            '<?php echo $this->getAllowedImageMimeTypesJson()?>',
            '<?php echo $this->getAllowedImageExtensions();?>'
        );
    }.bind(this));
</script>