<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2018 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use/
 * @version      Release: 2.6.0
 * @since        Available since Release 1.0.0
 */
?>
<?php $licenseEnabled =  $this->licenseAgreementsEnabled() && $this->getLicenceAgreementsText(); ?>

<div id="uploadedImages">
    <?php echo $this->getChildHtml('uploadedImages'); ?>
</div>
<?php if ($licenseEnabled):?>
    <ul class="form-list">
      <li class="control control-rights">
        <input type="checkbox" class="checkbox" name="licence_agreements" id="licence_agreements" />
        <label for="licence_agreements"><?php echo $this->__('I have the rights to use these images') ?></label>
        <div class="pd_more_info_link">
            <a href="javascript:;" id="license-agreements-link"><?php echo $this->__('More info') ?></a>
            <div id="license-agreemants" class="pd-license-agreements-popup" style="display: none">
                <?php echo $this->getLicenceAgreementsText(); ?>
            </div>
        </div>
      </li>
    </ul>
<?php endif;?>

<div id="upload-image-drop-zone" class="upload-image-drop-zone" <?php echo $licenseEnabled ? 'style="display:none;"' : ''?>>
    <?php echo $this->__('Drag an image here or <a href="javascript:void(0)">browse</a> for an image to upload.') ?>
    <?php if ($this->imageConditionsEnabled() && $text = $this->getImageConditionsText()): ?>
        <div id="image-conditions">
            <?php echo $text; ?>
        </div>
    <?php endif;?>
</div>
<div id="file-input-box" style="display: none;">
    <form target="iframeSave" id="uploadImages" enctype="multipart/form-data" action="<?php echo Mage::getUrl('designer/index/uploadImages'); ?>" method="post">
        <div class="pd-upload-input">
            <input name="filesToUpload[]" id="filesToUpload" type="file" multiple="multiple" accept="<?php echo $this->getAllowedImageMimeTypesString(); ?>"/>
        </div>
        <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getMaxUploadFileSize();?>" />
        <div class="pd-upload-buttons">
            <button class="button" type="submit"><span><span><?php echo $this->__('Upload'); ?></span></span></button>
        </div>
        <iframe id="iframeSave" name="iframeSave" style="display:none;"></iframe>
    </form>
    <?php if ($this->imageConditionsEnabled() && $text = $this->getImageConditionsText()): ?>
        <div id="image-conditions">
            <?php echo $text; ?>
        </div>
    <?php endif;?>
</div>
<div>
    <button class="button" id="remove-img-btn" type="button" <?php if (!$this->hasImages()):?>style="display: none"<?php endif;?>><span><span><?php echo $this->__('Remove Images'); ?></span></span></button>
</div>
<script type="text/javascript">
    document.observe('dom:loaded', function(e){
        var imagesUploader = new GoMage.ImageUploader(
            '<?php echo $this->getMaxUploadFileSize();?>',
            '<?php echo $this->getAllowedImageMimeTypesJson()?>',
            '<?php echo $this->getAllowedImageExtensions();?>',
            '<?php echo $this->getRemoveImgUrl();?>',
            '<?php echo Mage::getUrl('designer/index/uploadImages'); ?>'
        );
    }.bind(this));
</script>