<?php
/**
 * GoMage Product Designer Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2018 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use/
 * @version      Release: 2.6.0
 * @since        Available since Release 1.0.0
 */
?>
<?php if ($this->designButtonEnabled()): ?>
    <button type="button" title="<?php echo $this->__('Design It'); ?>" class="button btn-design" onclick="setLocation('<?php echo $this->getDesignUrl(); ?>');">
        <span><span><?php echo $this->__('Design It'); ?></span></span>
    </button>
<?php endif;?>