<?php
$_product = $this->getProduct();
//Is Product Navigation (Choose Product) Tab Enabled
$navigationEnabled = $this->isNavigationEnabled();

//Is Design (Add Design) Tab Enabled
$designEnabled = $this->isDesignEnabled() && $_product->getId();

//Is Text (Add Text) Tab Enabled
$textEnabled = $this->isTextEnabled() && $_product->getId();

//Is Image (Upload Image) Tab Enabled
$imageEnabled = $this->isUploadImageEnabled() && $_product->getId();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->helper('designer')->getProductPriceConfigJson(); ?>);
    function initProductDesigner() {
        var settings = {};
        settings.navigation = {
            chooseProduct : $("pd_choose_product"),
            addDesign : $("pd_add_design"),
            addText : $("pd_add_text"),
            addImage : $("pd_add_image"),
            designGallery : $("pd_design_gallery"),
            saveDesign: $("pd_save_design"),
            continue : $('pd_gt_product')
        };

        settings.controls = {
            undo: 'pd_undo',
            redo: 'pd_redo',
            flip_x: 'pd_flip_horizontal',
            flip_y: 'pd_flip_vertical',
            zoom: 'pd_zoom',
            allign_by_center: 'pd_allign_by_center'
        };

        settings.prices = <?php echo $this->getDesignPriceConfigJson(); ?>;
        settings.isCustomerLoggedIn = '<?php echo $this->isCustomerLoggedIn(); ?>';
        settings.isProductSelected = <?php echo $this->isProductSelected() ? 1 : 0; ?>;
        settings.isNavigationEnabled = <?php echo $this->isNavigationEnabled(); ?>;
        settings.isDesignedEnabled = <?php echo $this->isDesignEnabled(); ?>;
        settings.isTextEnabled = <?php echo $this->isTextEnabled(); ?>;
        settings.isUploadImageEnabled = <?php echo $this->isUploadImageEnabled(); ?>;
        settings.product = <?php echo $this->getEditorConfigJson(); ?>;
        settings.container = $("pd_container");
//        settings.pane = $("pd_pane");

        window.w = new GoMage.ProductDesigner(settings,
            '<?php echo Mage::getUrl('*/index/continue')?>',
            '<?php echo Mage::getUrl('*/customer/loginPost')?>',
            '<?php echo Mage::getUrl('*/customer/createPost')?>',
            '<?php echo Mage::getUrl('*/index/saveDesign')?>'
        );
    }
    document.observe("dom:loaded", function(e){
        initProductDesigner();
    }.bind(this));
</script>
<div id="product-designer">
    <div>
        <ul id="pd_nav_container" style="min-width: 600px;">
            <li style="display: <?php echo $navigationEnabled ? 'block': 'none'?>" id="pd_choose_product"><?php echo $this->__('Choose Product'); ?></li>
            <li style="display: <?php echo $designEnabled ? 'block': 'none'?>" id="pd_add_design"><?php echo $this->__('Add Design'); ?></li>
            <li style="display: <?php echo $textEnabled ? 'block': 'none'?>" id="pd_add_text"><?php echo $this->__('Add Text'); ?></li>
            <li style="display: <?php echo $imageEnabled ? 'block': 'none' ?>" id="pd_add_image"><?php echo $this->__('Upload Image'); ?></li>
        </ul>
        <ul id="pd_save_container" style="display: <?php echo $this->isProductSelected() ? 'block': 'none'?>">
            <li><button class="pd-btn" id="pd_save_design"><?php echo Mage::helper('designer')->__('Save  Design') ?></button></li>
            <li><button class="pd-btn" id="pd_gt_product"><?php echo Mage::helper('designer')->__('Continue') ?></button></li>
        </ul>
    </div>

    <div class="right sidebar">
        <div id="pd_panels">
            <!-- Product Designer Tabs -->
            <div id="pd_tabs">
                <?php if ($this->isNavigationEnabled()): ?>
                    <div class="pd-tab-content" id="pd_choose_product-content" style="display: block;">
                        <div class="pd-header"><?php echo $this->__('Choose Product'); ?></div>
                        <div class="pd-content">
                            <?php
                            // Product Navigation Block
                            // (template : base/default/template/gomage/productdesigner/catalog/product/filters.phtml)
                            echo $this->getChildHtml('productNavigator');
                            ?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if ($this->isDesignEnabled()): ?>
                    <div class="pd-tab-content" id="pd_add_design-content">
                        <div class="pd-header"><?php echo $this->__('Choose A Design'); ?></div>
                        <div class="pd-content">
                            <?php
                            // Add Image
                            // (template : gomage/productdesigner/design/choose_design.phtml)
                            echo $this->getChildHtml('addDesign');
                            ?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if ($this->isTextEnabled()): ?>
                    <div class="pd-tab-content" id="pd_add_text-content">
                        <div class="pd-header"><?php echo $this->__('Add Text'); ?></div>
                        <div class="pd-content">
                            <?php
                            // Add Image Text
                            // (template : gomage/productdesigner/design/text.phtml)
                            echo $this->getChildHtml('addText');
                            ?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if ($this->isUploadImageEnabled()): ?>
                    <div class="pd-tab-content" id="pd_add_image-content">
                        <div class="pd-header"><?php echo $this->__('Upload Images'); ?></div>
                        <div class="pd-content">
                            <?php
                            // Upload Image
                            // (template : gomage/productdesigner/design/upload_image.phtml)
                            echo $this->getChildHtml('uploadImage');
                            ?>
                        </div>
                    </div>
                <?php endif;?>
            </div>
            <!-- End Of Product Designer Tabs -->
        </div>
        <div id="additional_panels" style="display: <?php echo !$this->isProductSelected() ? 'none' : 'block'?>">
            <?php $config = $this->getEditorConfig(); ?>
            <div id="pd_sides" style="float: right;">
                <ul style="float: left">
                <?php $images = $this->getProductImages();?>
                <?php foreach ($images as $k => $v): ?>
                    <li style="float: left">
                        <img width="48" height="48" class="product-image" src="<?php echo $v['u'] ?>" data-id="<?php echo $k; ?>" data-image-id="<?php echo $v['id'] ?>">
                    </li>
                <?php endforeach ?>
                </ul>
                <script type="text/html" class="no-display" id="product-image-template">
                    <li style="float: left">
                        <img width="48" height="48" class="product-image" src="#{url}" data-id="#{image-id}" data-image-id="#{data-image-id}">
                    </li>
                </script>
            </div>
            <div id="product-colors" style="width: 100%; background: white">
                <?php if ($colors = $this->getProductColors()): ?>
                    <?php foreach($colors as $color): ?>
                        <?php if (isset($config['images'][$color['option_id']])):?>
                            <span class="color-btn <?php if ($color['option_id'] == $config['default_color']) echo 'selected'?>" color_id="<?php echo $color['option_id']?>" <?php if ($color['image']):?>style="background-image: <?php echo $color['image']; ?>"<?php endif;?>><?php if (!$color['image']): echo $color['value']; endif;?></span>
                        <?php endif;?>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
            <div id="additional_instructions">
                <?php echo $this->getChildHtml('additionalInstructions');?>
            </div>
        </div>
        <div id="design_price_container" class="product-designer-price">
            <?php echo $this->getChildHtml('design_price'); ?>
        </div>
    </div>

    <div class="content">
        <div id="pd_container"></div>
    </div>
        <div id="pd_bottom_panel" style="width: <?php echo $this->getProductImageWidth();?>px; display: <?php echo !$this->isProductSelected() ? 'none' : 'block'?>">
            <button class="pd-btn" id="pd_flip_horizontal"><?php echo Mage::helper('designer')->__('Horizontal Flip') ?></button>
            <button class="pd-btn" id="pd_flip_vertical"><?php echo Mage::helper('designer')->__('Vertical Flip') ?></button>
            <button class="pd-btn" id="pd_zoom"><?php echo Mage::helper('designer')->__('Zoom') ?></button>
            <button class="pd-btn" id="pd_allign_by_center"><?php echo Mage::helper('designer')->__('Align by center') ?></button>
            <button class="pd-btn" id="pd_undo"><?php echo Mage::helper('designer')->__('Undo') ?></button>
            <button class="pd-btn" id="pd_redo"><?php echo Mage::helper('designer')->__('Redo') ?></button>
        </div>
</div>
<?php if (!$this->getCustomerId()): ?>
    <?php echo $this->getChildHtml('customer.login');?>
    <?php echo $this->getChildHtml('customer.register');?>
<?php endif;?>