<?php
$w = 0;
if ($this->image_width < 800) {
    $w = 400 - round($this->image_width / 2);
}
?>
<div id="textsize">
    <?php echo $this->__('Width'); ?> <input type="text" name="areaWidth" id="areaWidth" value="0" /><?php echo $this->__('px'); ?>
    <?php echo $this->__('Height'); ?> <input type="text" name="areaHeight" id="areaHeight" value="0" /><?php echo $this->__('px'); ?>
</div>
<div id="image_wrapper" style="margin-left:<?php echo $w; ?>px;width:<?php echo $this->image_width; ?>px;height:<?php echo $this->image_height; ?>px;background: url(<?php echo $this->image->getUrl(); ?>) no-repeat center;border:1px solid #ccc">
    <canvas id="image" width="<?php echo $this->image_width; ?>" height="<?php echo $this->image_height; ?>"></canvas>
</div>

<div id="controls" class="form-buttons" style="margin-top:10px;width:100%;text-align:right;">
    <?php echo $this->__('Design Area used initial Cost'); ?>:
    <input type="text" id="initialPrice" name="initialPrice" value="<?php echo $this->settings['ip']?$this->settings['ip']:0; ?>" />
    <label for="side_selector"><?php echo Mage::helper('designer')->__('Choose a Side') ?> : </label>
    <select id="side_selector">
        <option value="1"><?php echo Mage::helper('designer')->__('Front') ?></option>
        <option value="2"><?php echo Mage::helper('designer')->__('Back') ?></option>
        <option value="3"><?php echo Mage::helper('designer')->__('Left') ?></option>
        <option value="4"><?php echo Mage::helper('designer')->__('Right') ?></option>
    </select>
    <button class="pd-btn scalable" type="button" id="save_settings"><?php echo Mage::helper('designer')->__('Save settings') ?></button>
</div>

<script type="text/javascript">
(function() {
    var options = $$('select#side_selector option');
    options['<?php echo $this->settings["s"] - 1; ?>'].selected = true;

    var imgW = '<?php echo $this->image_width; ?>';
    var imgH = '<?php echo $this->image_height; ?>'

    var canvas = new fabric.Canvas('image');

    var area = new fabric.Rect({
        top:    <?php echo $this->settings["t"]; ?>,
        left:   <?php echo $this->settings["l"]; ?>,
        width:  <?php echo $this->settings["w"]; ?>,
        height: <?php echo $this->settings["h"]; ?>,
        fill: '#d81417',
        opacity: 0.2
    });

    $('areaWidth').value = <?php echo $this->settings["w"] ?>;
    $('areaHeight').value = <?php echo $this->settings["h"] ?>;

    canvas.add(area);
    canvas.item(0).lockRotation = true;

    canvas.observe('object:moving', function(e) {
        var obj = e.target;
        var l = obj.get('left');
        var t = obj.get('top')
        var w = Math.round(obj.getWidth() / 2);
        var h = Math.round(obj.getHeight() / 2);

        if (l < w) {
            obj.set({left : w});
        }

        if (t < h) {
            obj.set({top : h});
        }

        if (l > canvas.getWidth() - w) {
            obj.set({left : canvas.getWidth() - w});
        }

        if (t > canvas.getHeight() - h) {
            obj.set({top : canvas.getHeight() - h});
        }
    });

    canvas.renderAll();

    var onTextChangeSize = function(element){
        element.observe('keyup', function() {
            var widthOrHeight = false;
            switch(element.id) {
                case 'areaWidth' : {
                    widthOrHeight = 'width';
                    break;
                }
                case 'areaHeight' : {
                    widthOrHeight = 'height';
                    break;
                }
                default: {
                    widthOrHeight = false;
                    break;
                }
            }
            if(typeof widthOrHeight === 'string') {
                area.set(widthOrHeight,parseInt(element.value));
                canvas.renderAll();
            }
        });
    };
    $$('#areaWidth, #areaHeight').each(onTextChangeSize);

    $('save_settings').observe('click', function() {
        var data = {};
        data['t'] = Math.round(area.getTop());
        data['l'] = Math.round(area.getLeft());
        data['w'] = Math.round(area.getWidth());
        data['h'] = Math.round(area.getHeight());
        data['s'] = $('side_selector').value;
        data['product_id'] = '<?php echo $this->product_id; ?>';
        data['image_id'] = '<?php echo $this->image_id; ?>';
        data['initial_price'] = $('initialPrice').value;

        new Ajax.Request('/designer/product/save', {
            method:'post',
            parameters: data,
            onSuccess: function(transport) {
                var response = transport.responseText || "no response text";
                window.parent.Windows.closeAll();
            },
            onFailure: function() {
                // TODO
                //alert('Something went wrong...');
            }
        });
    });
})();
</script>