<?php $availableFilters = $this->getAvailableFilters();?>
<?php $count = 0;?>
<ul class="form-list">
  <?php foreach ($availableFilters as $_filter):?>
    <?php if ($count == 0 || $count == 1):?>
    <li<?php echo $count === 1 ? "class='fields'" : ''?>>
    <?php endif;?>
    <?php if ($count == 1 || $count == 2): ?>
    <div class="field">
    <?php endif;?>
      <div class="input-box">
        <?php $options = $this->getAvailableFilterOptions($_filter);?>
        <select name="<?php echo $_filter?>" id="<?php echo $_filter?>_selector" class="filter_selector">
            <option value=""><?php echo $this->__('Select '. $_filter)?></option>
            <?php foreach ($options as $optionId => $label): ?>
                <option <?php echo $this->isFilterOptionSelected($_filter, $optionId) ? 'selected="selected"' : '';?>value="<?php echo $optionId;?>"><?php echo $label; ?></option>
            <?php endforeach;?>
        </select>
      </div>
    <?php if ($count == 1 || $count == 2): ?>
    </div>
    <?php endif;?>
    <?php if ($count == 0 || $count == 2):?>
    </li>
    <?php endif;?>
    <?php $count++;?>
  <?php endforeach;?>
</ul>