<?php $availableFilters = $this->getAvailableFilters();?>
<ul class="form-list">
  <?php foreach ($availableFilters as $_filter):?>
    <li>
      <div class="input-box">
        <?php $options = $this->getAvailableFiltersOptions($_filter);?>
        <select name="<?php echo $_filter?>" id="<?php echo $_filter?>_selector" class="filter_selector">
            <option value=""><?php echo $this->__('Select '. $_filter)?></option>
            <?php foreach ($options as $_option): ?>
                <option <?php echo $this->isFilterOptionSelected($_filter, $_option->getId()) ? 'selected="selected"' : '';?>value="<?php echo $_option->getId();?>"><?php echo $_option->getName(); ?></option>
            <?php endforeach;?>
        </select>
      </div>
    </li>
  <?php endforeach;?>
</ul>